### ISSUE TITLE
Be able to delete a step

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#106] opened 2022-05-26 02:23 UTC
* [x] MVP is just delete it which might put the graph into an invalid state #85 
* [x] If it is a flow step with valid ins and outs then remove it and rewire the two cuts ends back together so it remains valid
* [x] If it is a connector with valid ins and outs then remove it and rewire the two cuts ends back together so it remains valid

**Comment by keevan** [comment] 2022-05-26 03:32
Noting that this Is a duplicate of #85 with additional requirements

**Comment by brendanheywood** [comment] 2022-05-26 03:48
Lets make this one the more advanced stuff then with the relinking

**Comment by keevan** [comment] 2022-05-26 04:41
I'm okay with that.

So I'm understanding it correctly, with the join / split steps in mind (points 2 and 3), I'm guessing it should check and since the connection counts post-wiring will be invalid, it will stay detached?

**Comment by brendanheywood** [comment] 2022-05-26 05:10
If the ins and outs have the same count and type then we can safely rewire them, if count or types are different then we can't so it will just cut it into two sub graphs and force the admin to wire it back correctly.

**Closed** 2022-08-01 06:41 UTC
Labels: enhancement
